INSERT INTO todo_model(title) VALUES('title1');
INSERT INTO todo_model(title) VALUES('title2');
INSERT INTO todo_model(title) VALUES('title3');
INSERT INTO todo_model(title) VALUES('title4');
INSERT INTO todo_model(title) VALUES('title5');
INSERT INTO todo_model(title) VALUES('title6');
INSERT INTO todo_model(title) VALUES('title7');
INSERT INTO todo_model(title) VALUES('title8');
INSERT INTO todo_model(title) VALUES('title9');

INSERT INTO sample_board(title, description) VALUES('제목01', '내용01');
INSERT INTO sample_board(title, description) VALUES('제목02', '내용02');
INSERT INTO sample_board(title, description) VALUES('제목03', '내용03');
INSERT INTO sample_board(title, description) VALUES('제목04', '내용04');
INSERT INTO sample_board(title, description) VALUES('제목05', '내용05');
INSERT INTO sample_board(title, description) VALUES('제목06', '내용06');
INSERT INTO sample_board(title, description) VALUES('제목07', '내용07');
INSERT INTO sample_board(title, description) VALUES('제목08', '내용08');
INSERT INTO sample_board(title, description) VALUES('제목09', '내용09');
INSERT INTO sample_board(title, description) VALUES('제목10', '내용10');
INSERT INTO sample_board(title, description) VALUES('제목11', '내용11');
INSERT INTO sample_board(title, description) VALUES('제목12', '내용12');