INSERT INTO todo_model(title) VALUES('title1');
INSERT INTO todo_model(title) VALUES('title2');
INSERT INTO todo_model(title) VALUES('title3');
INSERT INTO todo_model(title) VALUES('title4');
INSERT INTO todo_model(title) VALUES('title5');
INSERT INTO todo_model(title) VALUES('title6');
INSERT INTO todo_model(title) VALUES('title7');
INSERT INTO todo_model(title) VALUES('title8');
INSERT INTO todo_model(title) VALUES('title9');